language: node_js
node_js:
  - "10.14.1"

addons:
  postgresql: "9.5"

services:
 - postgresql

before_script:
  - psql -c 'create database integration_tests;' -U postgres

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
